server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exojwt
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

application:
  jwt:
    secret: "Y2nr@Svs1#Rume@v9^r$$hwTm563QpxLfdDTO$VdLLMnNRJmcQ"
    headerPrefix: "Bearer "
    headerKey: "Authorization"
